- name: Update Repository
  ansible.builtin.apt:
    update_cache: true
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Make root Direktori
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: /var/www/projects/Ansible-Web, owner: www-data, group: www-data, mode: '0755'}
    - { path: /var/www/projects/Ansible-Web/mains, owner: www-data, group: www-data, mode: '0755' }    
    - { path: /var/www/projects/Ansible-Web/profiles, owner: www-data, group: www-data, mode: '0755' }
- name: Copy mains website files
  ansible.builtin.synchronize:
    src: ../WEB/mains/
    dest: /var/www/projects/Ansible-Web/mains/
    owner: yes
    group: yes
- name: Copy profiles website files
  ansible.builtin.synchronize:
    src: ../WEB/profiles/
    dest: /var/www/projects/Ansible-Web/profiles/
    owner: yes
    group: yes
- name: Move File Configuration
  ansible.builtin.copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/conf.d/ansible-nginx.conf
- name: Restart Service 
  ansible.builtin.service:
    name: nginx
    state: restarted