version: '3'
services:
  debian-server:
    build: .
    container_name: debian-server
    volumes:
      - ./NGINX/WEB:/var/www/  # Volumes untuk nginx website directory
      - ./datacenter:/home/datacenter  # Volumes untuk data center
      - ./datapublic:/home/datapublic  # Volumes untuk public data
    ports:
      - "80:80" 
      - "443:443" 
      - "53:53/udp"
      - "21:21"  
      - "139:139"  
      - "445:445"  
    tty: true
    stdin_open: true
